version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/barry/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  decks:
    container_name: decks
    build: .
    depends_on:
      - mongodb
    links:
      - mongodb
    command: npm run start
    ports:
      - 4000:4000
    volumes:
      - .:/decks
      - /decks/node_modules
    #env_file: .env.dev
    environment:
      NODE_ENV: dev
      PORT: 3003
