version: "3.8"

services:
  decks:
    container_name: decks
    build: .
    depends_on:
      - mongo-decks
    links:
      - mongo-decks
    command: npm run start
    ports:
      - 4000:4000
    volumes:
      - .:/decks
      - /decks/node_modules
    #env_file: .env.dev
    environment:
      NODE_ENV: dev
      PORT: 3003
  mongo-decks:
    image: excellalabs/mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGODB_APPLICATION_DATABASE: decks
      MONGODB_APPLICATION_USER: decks
      MONGODB_APPLICATION_PASS: 123456
