version: "3.8"

services:
  decks:
    container_name: decks
    build: .
    command: npm run start
    depends_on:
      - mongo-decks
    links:
      - mongo-decks
    ports:
      - 4000:4000
    volumes:
      - .:/usr/decks
      - /usr/decks/node_modules
    #env_file: .env.dev
    environment:
      NODE_ENV: dev
      PORT: 4000
  mongo-decks:
    image: mongo:latest #excellalabs/mongo
    container_name: mongo-decks
    ports:
      - "27017:27017"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/mongodb/database:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGODB_APPLICATION_DATABASE: decks
      MONGODB_APPLICATION_USER: decks
      MONGODB_APPLICATION_PASS: 123456
